version: "3.0"
services:
  web:
    image: nginx
    deploy:
      placement:
        constraints:
        - node.labels.dc == UK
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webserver
  visualizer:
# this does not work on MacOS
    image: dockersamples/visualizer:stable
    ports:
      - "8888:80"
    volumes:
      - "/var/run/docker.sock:var/run/docker.sock"
    deploy:
      placement:
        constraints:
        - node.Role == manager
    networks:
      - webserver
networks:
  webserver:
